name: spliceLauncher
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - r-base[version='>=4.0']
  - r-cairo[version='>=1.5']
  - r-writexls[version='>=6.3']
  - perl[version='>=5.13']
  - bedtools[version='>=2.17']
  - samtools[version='>=1.3']
  - star[version='>=2.6']
  - seqtk[version='>=1.3']
